#pragma once

#include "scene/Scene.h"
#include "scene/MenuScene.h"
#include "scene/Texture2DScene.h"
#include "scene/TriangleScene.h"
#include "scene/TransformationsScene.h"
#include "scene/Transformations3DScene.h"
#include "scene/Camera3DScene.h"
#include "scene/LightingScene.h"
#include "scene/MeshLoadingScene.h"
#include "scene/InstancingScene.h"
#include "scene/AsteroidScene.h"
#include "scene/DepthTestingScene.h"
#include "scene/BlendingScene.h"